module ActiveRecord       end
class  ActiveRecord::Base end
module ActiveRecord
  module AttributeMethods
    # = Active Record Attribute Methods \Read
    module Read
      extend ActiveSupport::Concern

      module ClassMethods
        private

        def define_method_attribute: (untyped canonical_name, owner: untyped, ?as: untyped) -> untyped
      end

      # Returns the value of the attribute identified by +attr_name+ after it
      # has been type cast. For example, a date attribute will cast "2004-12-12"
      # to <tt>Date.new(2004, 12, 12)</tt>. (For information about specific type
      # casting behavior, see the types under ActiveModel::Type.)
      def read_attribute: (untyped attr_name) { (?) -> untyped } -> untyped

      # This method exists to avoid the expensive primary_key check internally, without
      # breaking compatibility with the read_attribute API
      def _read_attribute: (untyped attr_name) { (?) -> untyped } -> untyped

      alias attribute _read_attribute
    end
  end
end
module ActiveRecord
  module AttributeMethods
    # = Active Record Attribute Methods \Write
    module Write
      extend ActiveSupport::Concern

      module ClassMethods
        private

        def define_method_attribute=: (untyped canonical_name, owner: untyped, ?as: untyped) -> untyped
      end

      # Updates the attribute identified by +attr_name+ using the specified
      # +value+. The attribute value will be type cast upon being read.
      def write_attribute: (untyped attr_name, untyped value) -> untyped

      # This method exists to avoid the expensive primary_key check internally, without
      # breaking compatibility with the write_attribute API
      def _write_attribute: (untyped attr_name, untyped value) -> untyped

      alias attribute= _write_attribute
    end
  end
end
module ActiveRecord
  module AttributeMethods
    # = Active Record Attribute Methods Before Type Cast
    #
    # ActiveRecord::AttributeMethods::BeforeTypeCast provides a way to
    # read the value of the attributes before typecasting and deserialization.
    #
    #   class Task < ActiveRecord::Base
    #   end
    #
    #   task = Task.new(id: '1', completed_on: '2012-10-21')
    #   task.id           # => 1
    #   task.completed_on # => Sun, 21 Oct 2012
    #
    #   task.attributes_before_type_cast
    #   # => {"id"=>"1", "completed_on"=>"2012-10-21", ... }
    #   task.read_attribute_before_type_cast('id')           # => "1"
    #   task.read_attribute_before_type_cast('completed_on') # => "2012-10-21"
    #
    # In addition to #read_attribute_before_type_cast and #attributes_before_type_cast,
    # it declares a method for all attributes with the <tt>*_before_type_cast</tt>
    # suffix.
    #
    #   task.id_before_type_cast           # => "1"
    #   task.completed_on_before_type_cast # => "2012-10-21"
    module BeforeTypeCast
      extend ActiveSupport::Concern

      # Returns the value of the attribute identified by +attr_name+ before
      # typecasting and deserialization.
      #
      #   class Task < ActiveRecord::Base
      #   end
      #
      #   task = Task.new(id: '1', completed_on: '2012-10-21')
      #   task.read_attribute('id')                            # => 1
      #   task.read_attribute_before_type_cast('id')           # => '1'
      #   task.read_attribute('completed_on')                  # => Sun, 21 Oct 2012
      #   task.read_attribute_before_type_cast('completed_on') # => "2012-10-21"
      #   task.read_attribute_before_type_cast(:completed_on)  # => "2012-10-21"
      def read_attribute_before_type_cast: (untyped attr_name) -> untyped

      # Returns the value of the attribute identified by +attr_name+ after
      # serialization.
      #
      #   class Book < ActiveRecord::Base
      #     enum :status, { draft: 1, published: 2 }
      #   end
      #
      #   book = Book.new(status: "published")
      #   book.read_attribute(:status)              # => "published"
      #   book.read_attribute_for_database(:status) # => 2
      def read_attribute_for_database: (untyped attr_name) -> untyped

      # Returns a hash of attributes before typecasting and deserialization.
      #
      #   class Task < ActiveRecord::Base
      #   end
      #
      #   task = Task.new(title: nil, is_done: true, completed_on: '2012-10-21')
      #   task.attributes
      #   # => {"id"=>nil, "title"=>nil, "is_done"=>true, "completed_on"=>Sun, 21 Oct 2012, "created_at"=>nil, "updated_at"=>nil}
      #   task.attributes_before_type_cast
      #   # => {"id"=>nil, "title"=>nil, "is_done"=>true, "completed_on"=>"2012-10-21", "created_at"=>nil, "updated_at"=>nil}
      def attributes_before_type_cast: () -> untyped

      # Returns a hash of attributes for assignment to the database.
      def attributes_for_database: () -> untyped

      private

      # Dispatch target for <tt>*_before_type_cast</tt> attribute methods.
      def attribute_before_type_cast: (untyped attr_name) -> untyped

      def attribute_for_database: (untyped attr_name) -> untyped

      def attribute_came_from_user?: (untyped attr_name) -> untyped
    end
  end
end
module ActiveRecord
  module AttributeMethods
    # = Active Record Attribute Methods \Query
    #
    # Adds query methods for attributes that return either +true+ or +false+
    # depending on the attribute type and value.
    #
    # For Boolean attributes this will return +true+ if the value is present
    # and return +false+ otherwise:
    #
    #   class Product < ActiveRecord::Base
    #   end
    #
    #   product = Product.new(archived: false)
    #   product.archived? # => false
    #   product.archived = true
    #   product.archived? # => true
    #
    # For Numeric attributes this will return +true+ if the value is a non-zero
    # number and return +false+ otherwise:
    #
    #   product.inventory_count = 0
    #   product.inventory_count? # => false
    #   product.inventory_count = 1
    #   product.inventory_count? # => true
    #
    # For other attributes it will return +true+ if the value is present
    # and return +false+ otherwise:
    #
    #   product.name = nil
    #   product.name? # => false
    #   product.name = " "
    #   product.name? # => false
    #   product.name = "Orange"
    #   product.name? # => true
    module Query
      extend ActiveSupport::Concern

      # Returns +true+ or +false+ for the attribute identified by +attr_name+,
      # depending on the attribute type and value.
      def query_attribute: (untyped attr_name) -> untyped

      def _query_attribute: (untyped attr_name) -> untyped

      alias attribute? query_attribute

      private

      def query_cast_attribute: (untyped attr_name, untyped value) -> untyped
    end
  end
end
module ActiveRecord
  module AttributeMethods
    # = Active Record Attribute Methods \Dirty
    #
    # Provides a way to track changes in your Active Record models. It adds all
    # methods from ActiveModel::Dirty and adds database-specific methods.
    #
    # A newly created +Person+ object is unchanged:
    #
    #   class Person < ActiveRecord::Base
    #   end
    #
    #   person = Person.create(name: "Allison")
    #   person.changed? # => false
    #
    # Change the name:
    #
    #   person.name = 'Alice'
    #   person.name_in_database          # => "Allison"
    #   person.will_save_change_to_name? # => true
    #   person.name_change_to_be_saved   # => ["Allison", "Alice"]
    #   person.changes_to_save           # => {"name"=>["Allison", "Alice"]}
    #
    # Save the changes:
    #
    #   person.save
    #   person.name_in_database        # => "Alice"
    #   person.saved_change_to_name?   # => true
    #   person.saved_change_to_name    # => ["Allison", "Alice"]
    #   person.name_before_last_save   # => "Allison"
    #
    # Similar to ActiveModel::Dirty, methods can be invoked as
    # +saved_change_to_name?+ or by passing an argument to the generic method
    # <tt>saved_change_to_attribute?("name")</tt>.
    module Dirty
      @mutations_before_last_save: untyped

      @mutations_from_database: untyped

      @_touch_attr_names: untyped

      @_skip_dirty_tracking: untyped

      extend ActiveSupport::Concern

      include ActiveModel::Dirty

      # <tt>reload</tt> the record and clears changed attributes.
      def reload: (*untyped) -> untyped

      # Did this attribute change when we last saved?
      #
      # This method is useful in after callbacks to determine if an attribute
      # was changed during the save that triggered the callbacks to run. It can
      # be invoked as +saved_change_to_name?+ instead of
      # <tt>saved_change_to_attribute?("name")</tt>.
      #
      # ==== Options
      #
      # [+from+]
      #   When specified, this method will return false unless the original
      #   value is equal to the given value.
      #
      # [+to+]
      #   When specified, this method will return false unless the value will be
      #   changed to the given value.
      def saved_change_to_attribute?: (untyped attr_name, **untyped options) -> untyped

      # Returns the change to an attribute during the last save. If the
      # attribute was changed, the result will be an array containing the
      # original value and the saved value.
      #
      # This method is useful in after callbacks, to see the change in an
      # attribute during the save that triggered the callbacks to run. It can be
      # invoked as +saved_change_to_name+ instead of
      # <tt>saved_change_to_attribute("name")</tt>.
      def saved_change_to_attribute: (untyped attr_name) -> untyped

      # Returns the original value of an attribute before the last save.
      #
      # This method is useful in after callbacks to get the original value of an
      # attribute before the save that triggered the callbacks to run. It can be
      # invoked as +name_before_last_save+ instead of
      # <tt>attribute_before_last_save("name")</tt>.
      def attribute_before_last_save: (untyped attr_name) -> untyped

      # Did the last call to +save+ have any changes to change?
      def saved_changes?: () -> untyped

      # Returns a hash containing all the changes that were just saved.
      def saved_changes: () -> untyped

      # Will this attribute change the next time we save?
      #
      # This method is useful in validations and before callbacks to determine
      # if the next call to +save+ will change a particular attribute. It can be
      # invoked as +will_save_change_to_name?+ instead of
      # <tt>will_save_change_to_attribute?("name")</tt>.
      #
      # ==== Options
      #
      # [+from+]
      #   When specified, this method will return false unless the original
      #   value is equal to the given value.
      #
      # [+to+]
      #   When specified, this method will return false unless the value will be
      #   changed to the given value.
      def will_save_change_to_attribute?: (untyped attr_name, **untyped options) -> untyped

      # Returns the change to an attribute that will be persisted during the
      # next save.
      #
      # This method is useful in validations and before callbacks, to see the
      # change to an attribute that will occur when the record is saved. It can
      # be invoked as +name_change_to_be_saved+ instead of
      # <tt>attribute_change_to_be_saved("name")</tt>.
      #
      # If the attribute will change, the result will be an array containing the
      # original value and the new value about to be saved.
      def attribute_change_to_be_saved: (untyped attr_name) -> untyped

      # Returns the value of an attribute in the database, as opposed to the
      # in-memory value that will be persisted the next time the record is
      # saved.
      #
      # This method is useful in validations and before callbacks, to see the
      # original value of an attribute prior to any changes about to be
      # saved. It can be invoked as +name_in_database+ instead of
      # <tt>attribute_in_database("name")</tt>.
      def attribute_in_database: (untyped attr_name) -> untyped

      # Will the next call to +save+ have any changes to persist?
      def has_changes_to_save?: () -> untyped

      # Returns a hash containing all the changes that will be persisted during
      # the next save.
      def changes_to_save: () -> untyped

      # Returns an array of the names of any attributes that will change when
      # the record is next saved.
      def changed_attribute_names_to_save: () -> untyped

      # Returns a hash of the attributes that will change when the record is
      # next saved.
      #
      # The hash keys are the attribute names, and the hash values are the
      # original attribute values in the database (as opposed to the in-memory
      # values about to be saved).
      def attributes_in_database: () -> untyped

      private

      def init_internals: () -> untyped

      def _touch_row: (untyped attribute_names, untyped time) -> untyped

      def _update_record: (?untyped attribute_names) -> untyped

      def _create_record: (?untyped attribute_names) -> untyped

      def attribute_names_for_partial_updates: () -> untyped

      def attribute_names_for_partial_inserts: () -> untyped
    end
  end
end
module ActiveRecord
  # = Active Record \Named \Scopes
  module Scoping
    module Named
      extend ActiveSupport::Concern

      module ClassMethods
        # Returns an ActiveRecord::Relation scope object.
        #
        #   posts = Post.all
        #   posts.size # Fires "select count(*) from  posts" and returns the count
        #   posts.each {|p| puts p.name } # Fires "select * from posts" and loads post objects
        #
        #   fruits = Fruit.all
        #   fruits = fruits.where(color: 'red') if options[:red_only]
        #   fruits = fruits.limit(10) if limited?
        #
        # You can define a scope that applies to all finders using
        # {default_scope}[rdoc-ref:Scoping::Default::ClassMethods#default_scope].
        def all: (?all_queries: untyped?) -> untyped

        def scope_for_association: (?untyped scope) -> untyped

        # Returns a scope for the model with default scopes.
        def default_scoped: (?untyped scope, ?all_queries: untyped?) -> untyped

        def default_extensions: () -> (untyped | ::Array[untyped])

        # Adds a class method for retrieving and querying objects.
        # The method is intended to return an ActiveRecord::Relation
        # object, which is composable with other scopes.
        # If it returns +nil+ or +false+, an
        # {all}[rdoc-ref:Scoping::Named::ClassMethods#all] scope is returned instead.
        #
        # A \scope represents a narrowing of a database query, such as
        # <tt>where(color: :red).select('shirts.*').includes(:washing_instructions)</tt>.
        #
        #   class Shirt < ActiveRecord::Base
        #     scope :red, -> { where(color: 'red') }
        #     scope :dry_clean_only, -> { joins(:washing_instructions).where('washing_instructions.dry_clean_only = ?', true) }
        #   end
        #
        # The above calls to #scope define class methods <tt>Shirt.red</tt> and
        # <tt>Shirt.dry_clean_only</tt>. <tt>Shirt.red</tt>, in effect,
        # represents the query <tt>Shirt.where(color: 'red')</tt>.
        #
        # Note that this is simply 'syntactic sugar' for defining an actual
        # class method:
        #
        #   class Shirt < ActiveRecord::Base
        #     def self.red
        #       where(color: 'red')
        #     end
        #   end
        #
        # Unlike <tt>Shirt.find(...)</tt>, however, the object returned by
        # <tt>Shirt.red</tt> is not an Array but an ActiveRecord::Relation,
        # which is composable with other scopes; it resembles the association object
        # constructed by a {has_many}[rdoc-ref:Associations::ClassMethods#has_many]
        # declaration. For instance, you can invoke <tt>Shirt.red.first</tt>, <tt>Shirt.red.count</tt>,
        # <tt>Shirt.red.where(size: 'small')</tt>. Also, just as with the
        # association objects, named \scopes act like an Array, implementing
        # Enumerable; <tt>Shirt.red.each(&block)</tt>, <tt>Shirt.red.first</tt>,
        # and <tt>Shirt.red.inject(memo, &block)</tt> all behave as if
        # <tt>Shirt.red</tt> really was an array.
        #
        # These named \scopes are composable. For instance,
        # <tt>Shirt.red.dry_clean_only</tt> will produce all shirts that are
        # both red and dry clean only. Nested finds and calculations also work
        # with these compositions: <tt>Shirt.red.dry_clean_only.count</tt>
        # returns the number of garments for which these criteria obtain.
        # Similarly with <tt>Shirt.red.dry_clean_only.average(:thread_count)</tt>.
        #
        # All scopes are available as class methods on the ActiveRecord::Base
        # descendant upon which the \scopes were defined. But they are also
        # available to {has_many}[rdoc-ref:Associations::ClassMethods#has_many]
        # associations. If,
        #
        #   class Person < ActiveRecord::Base
        #     has_many :shirts
        #   end
        #
        # then <tt>elton.shirts.red.dry_clean_only</tt> will return all of
        # Elton's red, dry clean only shirts.
        #
        # \Named scopes can also have extensions, just as with
        # {has_many}[rdoc-ref:Associations::ClassMethods#has_many] declarations:
        #
        #   class Shirt < ActiveRecord::Base
        #     scope :red, -> { where(color: 'red') } do
        #       def dom_id
        #         'red_shirts'
        #       end
        #     end
        #   end
        #
        # Scopes can also be used while creating/building a record.
        #
        #   class Article < ActiveRecord::Base
        #     scope :published, -> { where(published: true) }
        #   end
        #
        #   Article.published.new.published    # => true
        #   Article.published.create.published # => true
        #
        # \Class methods on your model are automatically available
        # on scopes. Assuming the following setup:
        #
        #   class Article < ActiveRecord::Base
        #     scope :published, -> { where(published: true) }
        #     scope :featured, -> { where(featured: true) }
        #
        #     def self.latest_article
        #       order('published_at desc').first
        #     end
        #
        #     def self.titles
        #       pluck(:title)
        #     end
        #   end
        #
        # We are able to call the methods like this:
        #
        #   Article.published.featured.latest_article
        #   Article.featured.titles
        def scope: (untyped name, untyped body) ?{ (?) -> untyped } -> untyped

        private

        def singleton_method_added: (untyped name) -> untyped
      end
    end
  end
end
